# Generated by Django 3.1.5 on 2021-02-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createBlog',
        ),
    ]
